### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by tajmone** [SicroAtGit/PB-RegEx-Engine#3]
You could enable Discussions to avoid cluttering Issues with anything that is not a pending task on the repository (e.g. Issue #1 could be converted to a Discussion, so once you've decided which shorthands to implement you can create an Issue for each pending shorthand, and keep it brief and to the point).

**Comment by SicroAtGit** [comment]
I have a little trouble deciding what should be an issue and what should be a discussion. With Issues, there is often still a discussion about the change as well.

I agree with you that the issue in question is too big and certainly better handled as a discussion.

**Comment by tajmone** [comment]
I tend to use Discussions for all planning, and then use Issues for repository specific interventions. It's a bit of a fuzzy boundary, after all even Discussion pertain to the repository, the main difference is trying to keep Issues on-topic, whereas Discussions can drift into side-considerations and other stuff that would clutter an Issue.

**Comment by SicroAtGit** [comment]
Ok, thanks.
