### ISSUE TITLE
Renaming 'Example_codes' folder

### ISSUE THREAD

**Issue by tajmone** [SicroAtGit/PB-RegEx-Engine#4]
You could rename the `Example_codes/` folder to just `examples/` and keep it short — after all, are there any examples rather than code here? And if there where, it would still be better to subfolder them (`examples/code/`, `examples/whatever/`, etc. rather than having `Example_codes/`, `Example_whatever/`, etc.).

Also, the noun _code_ (as in source code) [has no plural form](https://arstechnica.com/civis/viewtopic.php?t=63353) — it's just "code", never "codes" (unlike, e.g. "moral codes").

**Comment by SicroAtGit** [comment]
The directory is only for small code examples.

I will rename the directory to "examples" and adjust the sentence in [`README.md`](https://github.com/SicroAtGit/PB-RegEx-Engine/blob/a7c200a4aa7decd9d32795e50164c96196b04b29/README.md?plain=1#L40) accordingly from:

```
More example codes can be found in the [`Example_codes`](Example_codes) directory.
```

to

```
More code examples can be found in the [`examples`](examples) directory.
```

Thanks!
